---
# =================================================================================================
# Areas
# =================================================================================================
- name: area/docker
  color: "3970E4"
- name: area/github
  color: "000000"
- name: area/go
  color: "844FBA"

# =================================================================================================
# Renovate Types
# =================================================================================================
- name: renovate/go
  color: "844FBA"
- name: renovate/container
  color: "3970E4"
- name: renovate/github-action
  color: "000000"
